feat(context): add `Context::aspect_ratio`
tversteeg/chuot pull request #96
Opened 2024-07-03 15:48 UTC by suprohub

2024-07-03 16:19 UTC, tversteeg requested changes

2024-07-03 16:19 UTC, tversteeg commented on src/context/mod.rs
> +    /// - A `(numerator, denominator)` tuple
What does this return mean? How can these values be used and how they represent the aspect ratio? Could you add that to the description?

2024-07-03 16:34 UTC, suprohub commented on src/context/mod.rs
> +    /// - A `(numerator, denominator)` tuple
/// - A aspect ratio tuple?

2024-07-04 06:53 UTC, suprohub commented
i resolved

2024-07-04 07:11 UTC, tversteeg requested changes

2024-07-04 07:12 UTC, merged